package com.bms.utils;

import com.bms.model.Report;

/**
 * Formats report details into readable summaries or text output.
 */
public class ReportFormatter {

    // Format report details into a human-readable string
    public static String formatReport(Report report) {
        if (report == null) return "❌ No report found.";

        return "📋 Report Summary\n" +
               "---------------------\n" +
               "Report ID     : " + report.getReportId() + "\n" +
               "Type          : " + report.getReportType() + "\n" +
               "Generated By  : " + report.getGeneratedBy() + "\n" +
               "Date          : " + report.getGeneratedDate() + "\n" +
               "Description   : " + report.getDescription() + "\n";
    }

    // Example use:
    // System.out.println(ReportFormatter.formatReport(report));
}
